version: "3"

services:
        back1:
                container_name: app1
                restart: always
                build: .
                ports:
                        - "4000:4000"
                volumes:
                        - .:/app
                links:
                        - database1
        database1:
                image: mariadb
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
                        MYSQL_DATABASE: ${DATABASE_NAME}
                        MYSQL_USER: ${DATABASE_USER}
                        MYSQL_PASSWORD: ${DATABASE_PASSWORD}
                volumes:
                        - ./init:/docker-entrypoint-initdb.d

